### ISSUE TITLE
Use natsort in place of regex for neuralynx load

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/brody-lab-to-nwb#9]
look into using this instead to get properly sorted files https://pypi.org/project/natsort/

**Comment by bendichter** [comment]
No problem with using regex as is currently done, I more just wanted to let you know about this package. Feel free to use if you'd like

**Comment by CodyCBakerPhD** [comment]
natsort is now being used for all neuralynx interfaces
